FROM php:7.3-fpm

COPY ./ini/php.ini /usr/local/etc/php/php.ini
RUN apt update && \
    apt install -y \
        curl \
        libcurl3-dev \
        vim \
        git \
        zip \
        unzip \
        mcrypt \
        libjpeg-dev \
        libpng-dev \
        libbz2-dev \
        libzip-dev \
        libicu-dev \
        locales \
        libonig-dev \
        libpq-dev \
        zlib1g-dev 
RUN docker-php-ext-install \
        gd \
        bcmath \ 
        mysqli \
        pdo_mysql \
        intl \
        iconv \
        mbstring \
        zip \
        pgsql \
        pdo_pgsql
RUN pecl install xdebug-3.1.5
RUN docker-php-ext-enable xdebug
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer
