FROM php:7.3-fpm
RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini
RUN apt update && \
    apt install -y \
        vim \
        git \
        zip \
        unzip \
        mcrypt \
        libjpeg-dev \
        libpng-dev \
        libbz2-dev \
        libzip-dev \
        libicu-dev \
        locales \
        libonig-dev \
        libpq-dev \
        zlib1g-dev 
RUN docker-php-ext-install \
        gd \
        bcmath \ 
        mysqli \
        pdo_mysql \
        intl \
        iconv \
        mbstring \
        zip \
        pgsql \
        pdo_pgsql
RUN pecl install xdebug-3.1.5
RUN docker-php-ext-enable xdebug
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer
